### ISSUE TITLE
Module import with Vite throws `ReferenceError: document is not defined`

### ISSUE THREAD

**Issue by ulfaslak** [synesenom/dalian#25] opened 2022-04-13 12:36 UTC
I'm building a project with SvelteKit using the Vite bundler. I import dalian like this:

```JavaScript
import * as dalian from 'dalian';
```

This throws the following error on my webserver (only visible on my terminal):

```
ReferenceError: document is not defined
    at /Users/ulasje/Documents/git/project_frank/node_modules/dalian/dist/dalian.min.js:2:15515
    at /Users/ulasje/Documents/git/project_frank/node_modules/dalian/dist/dalian.min.js:2:69
    at Object.<anonymous> (/Users/ulasje/Documents/git/project_frank/node_modules/dalian/dist/dalian.min.js:2:289)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
```

Strangely, this makes the first page load fail, but upon reloading the page, everything displays correctly. I THINK it has something to do with Vite prebundling packages before sending anything to the browser, but I'm not sure.

I have not seen this bug with other packages.

**Comment by synesenom** [comment] 2022-04-13 19:17
The issue was caused by immediately invoked DOM operations in dalian. It is now fixed by #30 .

**Closed** 2022-04-14 10:10 UTC
